KE-1054 implement tag list contains filter
KE-works/pykechain pull request #1012
Opened 2021-07-07 09:41 UTC by KaczuH

Fixes #<issue>

## Checklist:
- [ ] My code follows the pykechain style
    - [ ] I added type hinting to all functions
    - [ ] I added documentation for all public functions
    - [ ] I locally used `tox` to check for dists and docs errors
    - [ ] My code passes the `pep8` and `flake8` linting checks and no warnings
    - [ ] I removed unused imports, using `Code > Optimize Imports` in PyCharm
    - [ ] I used [`black`](https://github.com/psf/black) to format the new code
- [ ] I have added tests that prove my fix is effective or that my feature works
    - [ ] I committed fresh test cassettes
    - [ ] I have proper test coverage (don't decline the coverage of the test)
- [ ] I asked another teammate to review the code
- [ ] I update the Changelog.md with the appropriate changes.

2021-07-09 08:16 UTC, raduiordache requested changes
There are a few tests failing. Can you make sure all tests are passing first, please?

2021-07-09 08:16 UTC, raduiordache commented on tests/test_contexts.py
> +    def test_retrieve_contexts_via_client_using_tags_list__contains_filter(self):
For me this test fails when I run it in Pycharm. It returns a `ConnectionError`.

2021-07-14 08:26 UTC, jberends commented
what is the sense of this PR? I only see an additional test in the changes. What was the original question to solve?

2021-07-14 08:27 UTC, raduiordache reviewed
I see only one test added. Does it mean that the filtering worked by default and needed no extra implementation?

2021-07-14 08:28 UTC, raduiordache requested changes
Don't forget to follow the checklist and add a Changelog message.

2021-07-14 09:56 UTC, KaczuH commented
@jberends  @raduiordache The filtering worked out of the box so i just added a test for it. Did i miss something?

2021-07-14 10:04 UTC, jberends commented
> @jberends @raduiordache The filtering worked out of the box so i just added a test for it. Did i miss something?

no.

please add changelog

2021-07-14 10:04 UTC, jberends approved these changes
- [ ] add changelog

2021-07-15 18:53 UTC, merged

2021-07-15 19:02 UTC, jberends commented
Woop woop!! First merge!!

> On 15 Jul 2021, at 20:53, KNiski ***@***.***> wrote:
> 
> ﻿
> Merged #1012 into master.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.