1108 nice to haves
KE-works/pykechain pull request #1118
Opened 2022-03-08 14:35 UTC by raduiordache

Fixes #<issue>

## Checklist:
- [ ] My code follows the pykechain style
    - [ ] I added type hinting to all functions
    - [ ] I added documentation for all public functions
    - [ ] I locally used `tox` to check for dists and docs errors
    - [ ] My code passes the `pep8` and `flake8` linting checks and no warnings
    - [ ] I removed unused imports, using `Code > Optimize Imports` in PyCharm
    - [ ] I used [`black`](https://github.com/psf/black) to format the new code
- [ ] I have added tests that prove my fix is effective or that my feature works
    - [ ] I committed fresh test cassettes
    - [ ] I have proper test coverage (don't decline the coverage of the test)
- [ ] I asked another teammate to review the code
- [ ] I update the Changelog.md with the appropriate changes.

2022-03-09 08:54 UTC, jberends requested changes
small changes

2022-03-09 08:54 UTC, jberends commented on pykechain/models/form.py
> +                "Could not process whether `Form` {} has part {}".format(self.id, part_id),
please use the f-strings

```suggestion
                f"Could not process whether `Form` {self.id} has part {part_id}",
```

2022-03-09 08:54 UTC, jberends commented on pykechain/models/form.py
> +
drop line

```suggestion
```

2022-03-09 08:54 UTC, jberends commented on pykechain/models/form.py
> +        url = self._client._build_url("forms_has_part",
did you use black here?

2022-03-09 16:49 UTC, raduiordache commented on pykechain/models/form.py
> +        url = self._client._build_url("forms_has_part",
I did now

2022-03-11 08:28 UTC, jberends approved these changes

2022-03-11 08:28 UTC, jberends commented on CHANGELOG.rst
> +: :+1: Removed the `target_scope` parameter when cloning inside the same scope
```suggestion
* :+1: Removed the `target_scope` parameter when cloning inside the same scope
```

2022-03-11 08:43 UTC, merged