897 - support of Python 3.8 has been added
KE-works/pykechain pull request #898
Opened 2020-12-01 12:28 UTC by raduiordache

Fixes #<issue>

## Checklist:
- [ ] My code follows the pykechain style
    - [ ] I added type hinting to all functions
    - [ ] I added documentation for all public functions
    - [ ] I locally used `tox` to check for dists and docs errors
    - [ ] My code passes the `pep8` and `flake8` linting checks and no warnings
    - [ ] I removed unused imports, using `Code > Optimize Imports` in PyCharm
    - [ ] I used [`black`](https://github.com/psf/black) to format the new code
- [ ] I have added tests that prove my fix is effective or that my feature works
    - [ ] I committed fresh test cassettes
    - [ ] I have proper test coverage (don't decline the coverage of the test)
- [ ] I asked another teammate to review the code
- [ ] I update the Changelog.md with the appropriate changes.

2020-12-01 12:32 UTC, raduiordache commented
That test is failing because we don't support Python 3.8 yet.

2020-12-01 14:19 UTC, jberends requested changes
fix failing test with smart assertions

2020-12-01 14:19 UTC, jberends commented on tests/test_services.py
> +        initial_env = ServiceEnvironmentVersion.PYTHON_3_8_NOTEBOOKS
this test fails in integration tests. Ensure that you assert both on `3.7 notebooks` and `3.8 notebooks` such that the test survives the changed backend defaults.

see: [line 182](https://github.com/KE-works/pykechain/pull/898/files#diff-caee650c3003842e9277d696a063ab724d42606e64cbf44cf1deb9d1d67d1d98R182)

2020-12-03 20:24 UTC, jberends approved these changes

2020-12-03 20:28 UTC, merged